### ISSUE TITLE
Where do I put my publish and subscribe keys?

### ISSUE THREAD

**Issue by jrdn91** [tomasbasham/ember-cli-pubnub#1]
After installing this I'm getting this error in the console

```
Uncaught TypeError: Cannot read property 'jsonp' of undefined
```

When I google this I see a SO post saying that the publish and subscribe keys need to be set, which makes sense, but the docs don't really outline how that's supposed to be done with this addon

**Comment by tomasbasham** [comment]
Sorry about this. I am currently in the process of implementing tests and updating the documentation. To install your keys, you should put them in the `environment.js` file as such:

```
var ENV = {
    ...

    PUBNUB: {
      subscribe_key: "KEY GOES HERE",
      publish_key: "KEY GOES HERE",
      ssl: true
    },

    contentSecurityPolicy: {
      'connect-src': "'self' http://*.pubnub.com"
    }
};
```

An updated README will be released soon and I'll definitely get these setup instructions in there. Let me know if this helps

**Comment by jrdn91** [comment]
Cool, I saw something that led me to that direction but I obviously then had no idea what it would have been expecting without diving further, thanks!
